export default [
    'ABS', 'AGI', 'AID', 'AIO', 'ANT', 'ATM', 'AUC', 'AVT',
    'BAT', 'BBN', 'BCH', 'BCI', 'BFT', 'BNT', 'BOX', 'BTC', 'BTG',
    'CBT', 'CFI', 'CND', 'CNN', 'CTX', 
    'DAD', 'DAI', 'DAT', 'DGX', 'DSH', 'DTA', 'DTH', 
    'EDO', 'ELF', 'EOS', 'ESS', 'ETC', 'ETH', 'ETP',
    'FSN', 'FUN',
    'GNT', 'GOT',
    'HOT',
    'IOS', 'IOT', 'IQX', 
    'KNC', 
    'LRC', 'LTC', 'LYM',
    'MAN', 'MGO', 'MIT', 'MKR', 'MNA', 'MTN', 
    'NCA', 'NEO', 'NIO',
    'ODE', 'OMG', 'ORS',
    'PAI', 'POA', 'POY', 
    'QSH', 'QTM',
    'RCN', 'RDN', 'REP', 'REQ', 'RLC', 'RRT', 'RTE', 
    'SAN', 'SEE', 'SEN', 'SNG', 'SNT', 'SPK', 'STJ', 
    'TKN', 'TNB', 'TRX',
    'UTK', 'UTN', 
    'VEE', 'VET',
    'WAX', 'WPR',
    'XLM', 'XMR', 'XRA', 'XRP', 'XTZ', 'XVG',
    'YYW',
    'ZCN', 'ZEC', 'ZIL', 'ZRX'
];